[package]
name = "common-type"
version.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
